apiVersion: v1
kind: Namespace
metadata:
  name: atlas-system
  labels:
    app.kubernetes.io/managed-by: pyinfra
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-core
  labels:
    app.kubernetes.io/managed-by: pyinfra
---
apiVersion: v1
kind: Namespace
metadata:
  name: atlas-gateway
  labels:
    app.kubernetes.io/managed-by: pyinfra
